name: amap_flutter_map
description: 高德地图SDK Flutter插件
version: 3.0.1
homepage: https://lbs.amap.com/
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_plugin_android_lifecycle: ^2.0.17
  plugin_platform_interface: ^2.1.6
  stream_transform: ^2.1.0

  amap_flutter_base:
    git:
      url: https://github.com/AlexV525/amap_flutter_base
      branch: main

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^5.4.2

flutter:
  plugin:
    platforms:
      android:
        package: com.amap.flutter.map
        pluginClass: AMapFlutterMapPlugin
      ios:
        pluginClass: AMapFlutterMapPlugin

  assets:
    - res/
